scott_passbook:
    resource: "@ScottPassbookBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path: /logout

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
