scott_passbook:
    resource: "@ScottPassbookBundle/Controller/"
    type:     annotation
    prefix:   /

scott_board:
    resource: "@ScottBoardBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
